/*
 * sx1276.h
 * Description: Header file for SX1276 LoRa Transmitter Driver
 */

#ifndef INC_SX1276_H_
#define INC_SX1276_H_

#include "main.h" // Ensures HAL and GPIO definitions are available

// -----------------------------------------------------------------------------
// HARDWARE PIN CONFIGURATION (UPDATED FOR CANSAT_V1)
// -----------------------------------------------------------------------------
extern SPI_HandleTypeDef hspi2;  // Your code uses SPI2!
#define SX_SPI_HANDLE    &hspi2

// Using the exact pin names generated by your STM32CubeIDE (.ioc)
#define SX_NSS_PORT      LORA_NSS_GPIO_Port
#define SX_NSS_PIN       LORA_NSS_Pin
#define SX_RESET_PORT    LORA_RST_GPIO_Port
#define SX_RESET_PIN     LORA_RST_Pin

// -----------------------------------------------------------------------------
// REGISTER MAP (LoRa Mode Focus)
// -----------------------------------------------------------------------------
#define REG_FIFO                 0x00
#define REG_OP_MODE              0x01
#define REG_FRF_MSB              0x06
#define REG_FRF_MID              0x07
#define REG_FRF_LSB              0x08
#define REG_PA_CONFIG            0x09
#define REG_OCP                  0x0B
#define REG_LNA                  0x0C
#define REG_FIFO_ADDR_PTR        0x0D
#define REG_FIFO_TX_BASE_ADDR    0x0E
#define REG_FIFO_RX_BASE_ADDR    0x0F
#define REG_IRQ_FLAGS            0x12
#define REG_MODEM_CONFIG_1       0x1D
#define REG_MODEM_CONFIG_2       0x1E
#define REG_PREAMBLE_MSB         0x20
#define REG_PREAMBLE_LSB         0x21
#define REG_PAYLOAD_LENGTH       0x22
#define REG_MODEM_CONFIG_3       0x26
#define REG_IMAGE_CAL            0x3B
#define REG_TEMP                 0x3C
#define REG_DIO_MAPPING_1        0x40
#define REG_DIO_MAPPING_2        0x41
#define REG_VERSION              0x42
#define REG_INVERT_IQ            0x33

// -----------------------------------------------------------------------------
// CONSTANTS & BIT DEFINITIONS
// -----------------------------------------------------------------------------
#define MODE_LONG_RANGE_MODE     0x80
#define MODE_SLEEP               0x00
#define MODE_STDBY               0x01
#define MODE_TX                  0x03
#define PA_BOOST                 0x80
#define IRQ_TX_DONE_MASK         0x08
#define BW_125_KHZ               0x70
#define BW_250_KHZ               0x80
#define CR_4_8                   0x08
#define SF_10                    0xA0
#define SF_8                     0x80
#define SF_7                     0x70
#define LOW_DATA_RATE_OPTIMIZE   0x08
#define AGC_AUTO_ON              0x04
#define REG_SYNC_WORD            0x39

// -----------------------------------------------------------------------------
// FUNCTION PROTOTYPES
// -----------------------------------------------------------------------------
void SX1276_Init(void);
void SX1276_SendPacket(uint8_t *payload, uint8_t size);
int8_t SX1276_GetTemperature(void);
void SX1276_WriteRegister(uint8_t reg, uint8_t value);
uint8_t SX1276_ReadRegister(uint8_t reg);
void SX1276_SendCalibrationPacket(uint32_t calibrationDuration);

#endif /* INC_SX1276_H_ */
